const CHANGE_CARD = 'CHANGE_CARD'
const CHANGE_WIDTH = 'CHANGE_WIDTH'
const DELETE_CARD = 'DELETE_CARD'
const UP_CARD = 'UP_CARD'
const DOWN_CARD = 'DOWN_CARD'
const ADD_CHILD_CARD = 'ADD_CHILD_CARD'

export {
   CHANGE_CARD,
   CHANGE_WIDTH,
   DELETE_CARD,
   UP_CARD,
   DOWN_CARD,
   ADD_CHILD_CARD
}
