const CHANGE_CARD = 'CHANGE_CARD'
const CHANGE_WIDTH = 'CHANGE_WIDTH'
const DELETE_CARD = 'DELETE_CARD'
const REBASE_CARDS = 'REBASE_CARDS'

export {
   CHANGE_CARD,
   CHANGE_WIDTH,
   DELETE_CARD,
   REBASE_CARDS
}
