const CREATE_CHILDREN_CARD = 'CREATE_CHILDREN_CARD'
const CHANGE_CHILDREN_CARD = 'CHANGE_CHILDREN_CARD'
const CHANGE_CHILDREN_WIDTH = 'CHANGE_CHILDREN_WIDTH'
// const ADD_CHILD_CARD = 'ADD_CHILD_CARD'
const DELETE_CHILDREN_CARD = 'DELETE_CHILDREN_CARD'
// const REBASE_CARDS = 'REBASE_CARDS'

export { CREATE_CHILDREN_CARD, CHANGE_CHILDREN_CARD, CHANGE_CHILDREN_WIDTH, DELETE_CHILDREN_CARD }